### ISSUE TITLE
libplplot18-5.15.0-shlibs-5.15.0-1: CMake Error at cmake/modules/plplot.cmake:404 (message): Cannot find required math library

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink-distributions#1100]
Attempting to upgrade `plplot-bin` fails with the following:
```
-- Found SWIG: /opt/sw/bin/swig (found version "3.0.12")  
-- SWIG_VERSION = 3.0.12
-- Found Perl: /usr/bin/perl (found version "5.30.2") 
CMake Error at cmake/modules/plplot.cmake:404 (message):
  Cannot find required math library
Call Stack (most recent call first):
  CMakeLists.txt:159 (include)


-- Configuring incomplete, errors occurred!
See also "/opt/sw/src/fink.build/libplplot18-5.15.0-shlibs-5.15.0-1/plplot-5.15.0/finkbuild/CMakeFiles/CMakeOutput.log".
See also "/opt/sw/src/fink.build/libplplot18-5.15.0-shlibs-5.15.0-1/plplot-5.15.0/finkbuild/CMakeFiles/CMakeError.log".
-- Cache values
```
...and then the cache values go on for a ways; do you want them all?
Here are the files it said to check:
- `CMakeOutput.log`: [CMakeOutput.log](https://github.com/fink/fink-distributions/files/13258571/CMakeOutput.log)
- `CMakeError.log`: [CMakeError.log](https://github.com/fink/fink-distributions/files/13258572/CMakeError.log)

(I'm on x86_64 Big Sur with Xcode 13)

**Comment by cooljeanius** [comment]
Ah, checking the error log shows that this is yet another example of `-Werror=implicit-function-declaration` being on by default now:
```
Building C object CMakeFiles/cmTC_5ae61.dir/TestForHighBitCharacters.c.o
/opt/sw/var/lib/fink/path-prefix-clang/cc   -MD  -MD -MT CMakeFiles/cmTC_5ae61.dir/TestForHighBitCharacters.c.o -MF CMakeFiles/cmTC_5ae61.dir/TestForHighBitCharacters.c.o.d -o CMakeFiles/cmTC_5ae61.dir/TestForHighBitCharacters.c.o -c /opt/sw/src/fink.build/libplplot18-5.15.0-shlibs-5.15.0-1/plplot-5.15.0/cmake/modules/TestForHighBitCharacters.c
/opt/sw/src/fink.build/libplplot18-5.15.0-shlibs-5.15.0-1/plplot-5.15.0/cmake/modules/TestForHighBitCharacters.c:20:8: error: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]
       exit(1);
       ^
/opt/sw/src/fink.build/libplplot18-5.15.0-shlibs-5.15.0-1/plplot-5.15.0/cmake/modules/TestForHighBitCharacters.c:20:8: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
1 error generated.
make[1]: *** [CMakeFiles/cmTC_5ae61.dir/build.make:79: CMakeFiles/cmTC_5ae61.dir/TestForHighBitCharacters.c.o] Error 1
make[1]: Leaving directory '/opt/sw/src/fink.build/libplplot18-5.15.0-shlibs-5.15.0-1/plplot-5.15.0/finkbuild/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_5ae61/fast] Error 2
```

**Comment by dmacks** [comment]
Possibly fixed by 9d0a5e156cc1d6a3e147c860ccc95159bc91c47b

**Comment by cooljeanius** [comment]
> Possibly fixed by [9d0a5e1](https://github.com/fink/fink-distributions/commit/9d0a5e156cc1d6a3e147c860ccc95159bc91c47b)

Well, the error log no longer has the instance of `-Werror=implicit-function-declaration` in it, but the test for the math library is still failing, so I dunno what's going wrong...

**Comment by dmacks** [comment]
Baby steps:) Implicit-declarations are easy to trigger on any platform and fix; the libm only occurs on certain newer OS X (it's about SDK and library caching, not the compiler itself). Maybe 4eceb1ef6be18670cfe0f590cbde8618049f5a14 ?

**Comment by cooljeanius** [comment]
> Baby steps:) Implicit-declarations are easy to trigger on any platform and fix; the libm only occurs on certain newer OS X (it's about SDK and library caching, not the compiler itself). Maybe [4eceb1e](https://github.com/fink/fink-distributions/commit/4eceb1ef6be18670cfe0f590cbde8618049f5a14) ?

OK, that seems to have done it; thanks!
