### ISSUE TITLE
Package python27-2.7.16-1 fails to build

### ISSUE THREAD

**Issue by remkos** [fink/fink-distributions#363]
The latest python27-2.7.16-1 builds python, but the package cannot be completed as nine of the modules fail to build. Apparently only 9 failures are expected.
Maybe there are some missing `BuildDepends`?
Or the CFLAGS should use `-I$SDK_PATH/usr/include` instead of `-isysroot $SDK_PATH`?

The error message:
<pre>Python build finished, but the necessary bits to build these modules were not found:
bsddb185           dl                 imageop
linuxaudiodev      nis                ossaudiodev
spwd               sunaudiodev        zlib
To find the necessary bits, look in setup.py in detect_modules() for the module's name.
(Fink package build should have 7 missing)
</pre>

Building on MacOS 10.14.3 with Command Line Tools 10.1

**Comment by remkos** [comment]
The fix for this issue is indeed replacing  `-isysroot $SDK_PATH` by  `-I$SDK_PATH/usr/include` as suggested above.
See PR #364.

**Comment by danielj7** [comment]
Fixed by https://github.com/fink/fink-distributions/pull/364

**Comment by gaboentropy** [comment]
I have this problem with python27 1:2.7.16-2
SO it seems like the problem was not fixed. My mac has mojave.

**Comment by emmomp** [comment]
I am also getting this error installing  python27-2.7.17-1 with the following 
Package manager version: 0.45.0
Distribution version: selfupdate-rsync Mon Oct 28 14:26:35 2019, 10.14.5, x86_64
Trees: local/main stable/main
Xcode.app: 11.1
Xcode command-line tools: 10.3.0.0.1.1562985497

**Comment by sth0** [comment]
There is a mismatch between Xcode and the command line tools.

Try updating the command line tools to version 11.1, I think you need to download them explicitly from the developer site.
<https://developer.apple.com <https://developer.apple.com/>>

There are still some packages that do not build under Xcode 11.1 so you may have found one of them.

-Scott
